test_solana_program:
	cargo test-bpf --features no-mint-check no-bond-signer v1-instructions-allowed -- --nocapture
	https://ap-production.fra1.digitaloceanspaces.com/244da0ce-5606-11ee-8dff-e22cc3038c7c